# Generated by Django 4.1.7 on 2023-03-24 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_driver_added_alter_truck_truck_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='language_other',
            field=models.CharField(blank=True, max_length=50, verbose_name='Language (Other)'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed.', regex='^[a-zA-Z]+([-][a-zA-Z]+)?$')], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='district',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed.', regex='^[a-zA-Z]+([-][a-zA-Z]+)?$')], verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driverName',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only alphabets allowed.', regex='^[a-zA-Z]+([-][a-zA-Z]+)?$')], verbose_name='Driver Name'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('MS', 'Malay'), ('ZH', 'Chinese'), ('OTHER', 'Other')], max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='number_plate',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter valid format.', regex='^[a-zA-Z0-9]+$')], verbose_name='Number Plate'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='registration_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter valid format.', regex='^[a-zA-Z0-9]+$')], verbose_name='Registration Number'),
        ),
    ]
