# Generated by Django 4.1.7 on 2023-03-23 06:44

from django.db import migrations, models
import django.db.models.deletion
import driver.models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_assigned_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='assigned_truck',
            field=models.ForeignKey(default=driver.models.get_default_status, on_delete=django.db.models.deletion.SET_DEFAULT, to='driver.truck'),
        ),
    ]
