# Generated by Django 4.1.7 on 2023-03-23 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_driver_assigned_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
