# Generated by Django 4.1.7 on 2023-03-24 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_language_other_alter_driver_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='language_other',
        ),
        migrations.AlterField(
            model_name='driver',
            name='mobile_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Please input digits only.', regex='^[0-9]{10,11}$')], verbose_name='Mobile Number'),
        ),
    ]
